# Generated by Django 5.1.7 on 2025-06-06 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_price_orderitem_unit_price'),
        ('products', '0008_productvariation_unit_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
