# Generated by Django 5.1.7 on 2025-06-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_product_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
