# Generated by Django 5.1.7 on 2025-05-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_url_productimage_image_productvariation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
    ]
