# Generated by Django 5.1.7 on 2025-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_price_productvariation_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
