# Generated by Django 5.1.7 on 2025-05-27 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariation_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='variations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_main', models.BooleanField(default=False)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariation')),
            ],
        ),
    ]
