# Generated by Django 5.1.7 on 2025-06-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_variationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='unit_measurement',
            field=models.CharField(default='per kg', max_length=100),
        ),
    ]
