# Generated by Django 5.1.7 on 2025-06-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariation_unit_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('out_of_stock', 'Out of Stock'), ('hidden', 'Hidden'), ('pending_approval', 'Pending Approval'), ('deleted', 'Deleted')], default='published', max_length=20),
        ),
    ]
