# Generated by Django 5.1.7 on 2025-06-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage_image_url_variationimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='variationimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='variationimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='variations/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variationimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
